### ISSUE TITLE
Notify when users enter/leave the channel

### ISSUE THREAD

**Issue by mxm** [ekmartin/slack-irc#58] opened 2015-09-23 12:44 UTC
Sending messages back and forth between Slack and IRC really works great. However, when responding to a user via Slack one often runs into the problem that the user has already left the channel. How much work would it be to send notifications to the Slack channel upon IRC join/leave events? This feature should be configurable.

**Comment by robertkety** [comment] 2015-09-23 14:08
I added a welcome message feature in pull request 55. The feature was rejected because there are other bots that have this feature. However, it's easy enough to add it to your bot.js file. Let me know if you have any issues adding it from pull request 55.

**Comment by mxm** [comment] 2015-09-23 15:00
Thanks @robertkety. Just took a look at #55. It looks fairly easy to modify it according to my feature request.

**Comment by ekmartin** [comment] 2015-09-23 15:12
If I'm not misunderstanding completely, what @mxm is referring to here is rather what you've implemented in #54 (i.e. join/quit messages from IRC to Slack) and not the welcome messages from #55.

**Comment by robertkety** [comment] 2015-09-23 15:14
54 will have join and part, but 55 has the configurable message.

On Wed, Sep 23, 2015 at 8:12 AM, Martin Ek < notifications@github.com [notifications@github.com] > wrote:
If I'm not misunderstanding completely, what @mxm [https://github.com/mxm] is referring to here is rather what you've implemented in #54 [https://github.com/ekmartin/slack-irc/pull/54] (i.e. join/quit messages from IRC to Slack) and not the welcome messages from #55 [https://github.com/ekmartin/slack-irc/pull/55] .

—
Reply to this email directly or view it on GitHub
[https://github.com/ekmartin/slack-irc/issues/58#issuecomment-142635145] .[https://github.com/notifications/beacon/AF6-kIdfwc74XzZZffN_K8rizjWLImxDks5o0rjegaJpZM4GCUSE.gif]

**Comment by mxm** [comment] 2015-09-23 15:18
Yes I understood that #55 is the other way around but it's easy to change that. Now that I see #54, I don't even have to do that because it is pretty much what I want.

**Comment by mxm** [comment] 2015-09-23 15:20
Closing this one to continue the discussion in #54.

**Comment by mxm** [comment] 2015-09-24 10:17
Actually, let's keep this open until #54 is merged.

**Comment by ekmartin** [comment] 2015-09-24 17:29
Pretty much a duplicate of #32 though, so probably enough to just have that open.

**Closed by ekmartin** 2015-09-24 17:29 UTC
